### ISSUE TITLE
test_04_ConversionPrintingToggle() Inquiry

### ISSUE THREAD

**Issue by marctan** [google/cloudprint_logocert#117]
This test will try to disable the conversion_print first then will try to localprint an .svg file.

It will then verify if the printer has been able to print the .svg file by checking the job_id if it's empty or not. 
See snippet below:

```
print 'Conversion printing successfully turned off'

    job_id = _device.LocalPrint(test_name, Constants.IMAGES['SVG1'], self.cjt,
                                'image/svg+xml', check_supported_content=False)
    try:
      self.assertIsNone(job_id)
    except AssertionError:
      notes = 'Able to print via privet conversion printing when disabled.'
      notes += ' Check if the filetype svg is supported locally by the printer.'
      self.LogTest(test_id, test_name, 'Failed', notes)
      raise
    else:
      notes = ('Not able to print file locally when conversion print is '
               'disabled.')
```

Everything is working fine. The job_id is empty as expected since conversion_printing is turned off and the printer does not support the svg filetype.  

But I would like to clarify why it still printed a 1 page job. As you can see from the image below, it printed the directory of a pdf file from the test tool. 
![1](https://cloud.githubusercontent.com/assets/19194749/26826344/5330f364-4aeb-11e7-8dc2-b5431c6e1d32.JPG)

Is this expected behavior? This was reproduced using Windows 10 and Windows 8 and using the V2 Tool.
Thanks!

**Comment by lrbom** [comment]
Hi Marc,

Thanks for bringing this issue to our attention.

When kicking off a local print job via /submitdoc fails, we try to fail gracefully by cancelling the local print job. However, since there is no official API to cancel a local print job, we simply send a string to be printed using the same job ID that was created in a prerequisite step, /createjob.

I have clarified the output in the tool so users will now know why the extra page is being printed. I've also replaced the mysterious file path with an informative string. :)

Commit: https://github.com/google/cloudprint_logocert/commit/dad14448f2abc66487ba812e60dc8b27e239b62a

Please pull from master to get the latest changes.

Thanks!
Kevin

**Comment by marctan** [comment]
That makes sense! 
Will pull this change and will verify this again.

Thanks!

**Comment by marctan** [comment]
This is now resolved. Thanks!
