### ISSUE TITLE
Printers which have no "resolved issues" fail.

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#118]
Printers which have no "resolved issues" send the "certification_id" field without "resolved_issue" field on /register and /update API.
(These fields are documented in "Firmware Issue Resolution" version 1.0.)
And the GCP server does not produce "resolvedIssues" field in CDD for these printers.

Finally, these printers fail the "testCapsResolvedIssues" test, because this test expects that the "resolvedIssues" field is in CDD.

I think it's better to remove this test from the tool.

**Comment by lrbom** [comment]
After reviewing the "Firmware Issue Resolution" doc, I agree that this field can be omitted in the CDD.

Instead of removing this test altogether, I updated the test to check that 'resolvedIssues' is either missing or empty. Please let me know if you have any questions.

commit: https://github.com/google/cloudprint_logocert/commit/7193bc974ff82946ae79653faf83b73255e71a36

Thanks!

**Comment by YasuhiroFuruta** [comment]
Thank you for your quick commit.

The commit makes printers which have no "resolved issues" pass, 
but printers which **have** "resolved issues" fail.

Are there any printers which have "resolved issues" in the world?

If yes, I think removing the testcase or adding CAPS option is required.

**Comment by lrbom** [comment]
There are indeed printers that have "resolvedIssues" in the world; however, those printers have only experienced **minor** firmware fixes and do not require a full certification. For those printers, the Logocert tool is not necessary to be run as the fixes can be confirmed manually.

This tool is meant to be run for the following:
1. Printers that have never been certified
2. Printers that require re-certification due to **major** fixes in firmware

In both of the cases, the printers should not have "resolvedIssues" as they have not been certified yet. 

Of course this tool can still be run on certified printers **with** "resolvedIssues" as a sanity check, but this test case can simply be ignored. Please let me know if you see any other issues with leaving this test case in. 

Thanks!

**Comment by YasuhiroFuruta** [comment]
Thank you for your answer.
I understand it!

Every printer has **no** "resolved issues" at the certification test.
