### ISSUE TITLE
test_17_LocalPrintPWGColorSelect:Color option of CJT has no vendor_id key.

### ISSUE THREAD

**Issue by YYWeave** [google/cloudprint_logocert#126]
I am failing on the test_17_LocalPrintPWGColorSelect.
The 2nd print job cannot be printed in monochrome.

But the setting of color or monochrome is working correctly when I take a local printing by manual.

I compared the packets and found the diffrence below.
Color option in CJT when test_17_LocalPrintPWGColorSelect is running:
{"color": {"type": "STANDARD_COLOR"}}

Color option in CJT when taking a local printing with setting of color by manual:
{"color": {"type": "STANDARD_COLOR","vendor_id": "Color"};

There is no vendor_id in the former one.
Our printers have a type and vendor_id option in the color capability,
So the CJT should include both of them.
The CJT from test_17_LocalPrintPWGColorSelect which only has type would not be parsed correctlly in our printers.

Please have a confirm on this test.
Thank you so much!

**Comment by lrbom** [comment]
From the CJT specification - https://developers.google.com/cloud-print/docs/cdd#cjt

![image](https://user-images.githubusercontent.com/23246871/27307756-1f272268-5500-11e7-8509-5877225536d5.png)

Only the 'type' field is required so 'vendor_id' should not be necessary for the printer to local print properly. Even though the test passes manually through Chrome since it adds in the 'vendor_id' field behind the scenes, the tool aims to test that the printer strictly follows the specifications.

**Comment by YYWeave** [comment]
I fixed the issue and now our device passed the color setting testcases.
Thank you for your advice.

**Comment by lrbom** [comment]
Awesome, thanks!
