### ISSUE TITLE
Error in setUpModule

### ISSUE THREAD

**Issue by tblossfeld** [google/cloudprint_logocert#28]
I am getting an error in the setUpModule as seen here. Note that this script is being run on Windows 7.

![setupmodule](https://cloud.githubusercontent.com/assets/17885939/15577835/1fb7b4e2-232c-11e6-85d4-a1a9a407dfe1.png)

**Comment by kdlucas** [comment]
It looks like the mdns service didn't get fully added, as mdsn_browser.listener.discovered[k]['info'] should have been set once it was discovered. It get set in line 49 of _mdns.py. Try adding some statements in the setUpModule like:

under line 130:
  for k in mdns_browser.listener.discovered:
    print mdsn_browser.listener.discovered[k]

and then you can see what keys have been set for each value of k. The purpose of this code is to discover which port Privet is using.

**Comment by tblossfeld** [comment]
I have added the line in as instructed with the following results. Not entirely sure what it means.

![setupmodule3](https://cloud.githubusercontent.com/assets/17885939/15681874/17b772fe-2729-11e6-9bb1-ce7d6a3be75f.png)

**Comment by kdlucas** [comment]
Let me look through the code and see why this dictionary key is not getting set.

**Comment by kdlucas** [comment]
I wonder if you have the latest version of _mdns.py, as we recently made some changes to that file. Please check that, as I notice an older copy of _mdns.py would cause this issue.

**Comment by tblossfeld** [comment]
I recently downloaded the zip file found here: http://google.github.io/cloudprint_logocert/ after noticing a change made to testcert.py.

I compared the version of _mdns.py in my working directory with the version on github, and they are identical.

**Comment by kdlucas** [comment]
Ok, I'm going to run some of these commands from the command line and I'll
see if I can't figure out why that key isn't getting set.

Kelly
kdLucas

**Comment by kdlucas** [comment]
I just tested this and it looks to be working ok. In your particular case, in order to see what is going on, edit _log.py and change the debug log level from info to debug. Then re-run testcert.py. If you're on Linux you should see some log files under /tmp/ . Open the log file and look for a statement like this:

2016-06-02 12:46:04,603, LogoCert INFO: Service added: "8D0F7D61-A70A-4816-AF60-8C04E3CF1593._privet._tcp.local." (type is _privet._tcp.local.)

Then, after that statement there should be a follow on statement like this:

2016-06-02 12:46:05,231, LogoCert DEBUG: 8D0F7D61-A70A-4816-AF60-8C04E3CF1593._privet._tcp.local. service info: ServiceInfo(type='_privet._tcp.local.', name=u'8D0F7D61-A70A-4816-AF60-8C04E3CF1593._privet._tcp.local.', address='\xc0\xa8\x04\xa5', port=80, weight=0, priority=0, server=u'linux-5.local.', properties={'mmid': 'AAw7x', 'ty': 'LED Flasher', 'note': 'Controls on-board LEDs', 'flags': 'CB', 'services': 'vendor', 'txtvers': '3', 'id': '44D38A8A-6E02-4A4B-885E-8FED36E68D3E'})

That 2nd string with "service info" in it means the 'info' key has been set properly. If that is missing, than there must be some issue with the mdns broadcast of the printer.
