### ISSUE TITLE
GCP Logo Certification GitHub Tool: For XMPP add TLS Check in Automation Script

### ISSUE THREAD

**Issue by surenderkodam** [google/cloudprint_logocert#30]
Update GCP Logo Certification test automation script suite for XMPP to include a check for TLS (formerly known as SSL) as soon as possible as this is needed for future remaining GCP 2.0 Logo Certifications. Going forward we will not be able to certify partner devices (printers) that do not use TLS for XMPP. Thus, we need to update our automation to check that Google GCP partners use TLS for XMPP, in terms of XMPP client-to-server communications. 

This change is needed in order to not allow for the XMPP service to accept authentication credentials in cleartext and transmit user data in cleartext. We need the TLS protocol to provide a way to secure an application protocol from intercepted and tampered with. In terms of stream-based protocol communication, clients must initiate a TLS session immediately after connecting, before beginning the normal XML stream.

**Comment by kdlucas** [comment]
It looks like using XMPP requires TLS, so I don't think our Logo Certification tool needs to verify this. Here is Google's requirements for XMPP:

https://developers.google.com/talk/open_communications

And more background info:

Google Talk uses Extensible Messaging and Presence Protocol (XMPP) and XMPP Extension Protocols (XEP). Google's XMPP communication uses TCP Port 5222, with all traffic encrypted using TLS. Google Talk forces authentication to take place with Google's Single Sign-On (SSO) token, as noted by the X-GOOGLE-TOKEN mechanism. The SSO is conducted over SSL before the XMPP communication process occurs, which protects the user's credentials. 

Because the SSO authentication process takes place over TLS and XMPP media are wrapped over TLS, encryption protects the username, password, and media while they are in transit. The use of TLS for authentication and media transfer is required to use Google Talk.
