### ISSUE TITLE
Job state checking is too early

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#35]
The test cases "testMalformattedFile" and "testJobStateEmptyInputTray" are checking the job state after 10 seconds from submitting the job.

The test case "testMalformattedFile" expects the job state is "Printed", but the job state is still "In progress" on some printer because the printer is printing the job at that time.
The test case "testJobStateEmptyInputTray" expects the job state is "Error", but the job state is still "In progress" on some printer because the printer is trying to feed a paper at that time.
10 seconds are too short.

I think these test cases should wait until the job state becomes a state other than "In progress" before checking that.

**Comment by kdlucas** [comment]
That might be a good idea, to implement a retry mechanism that makes sure
the job gets out of the IN_PROGRESS state. I'll see how easy it would be to
implement this.

Kelly
kdLucas

**Comment by marctan** [comment]
Hi Yasuhiro, Kelly,

Requesting to also include checking if printer is still in 'QUEUED' state in WaitJobStatusNotIn().

Since sometimes internet connection is really really slow so the job is still in 'QUEUED' state. Please have these tests modified to avoid failure and for it to be more robust. 
The ff test scripts are listed below:

**testJobStateEmptyInputTray** - in WaitJobStatusNotIn() parameter include 'QUEUED'  state

**testJobStateMissingToner** - use WaitJobStatusNotIn() and include 'QUEUED' state in parameter instead of using getjobstatus()

**testJobStateNetworkOutage** - use WaitJobStatusNotIn() and include 'QUEUED' state in parameter instead of using getjobstatus()

**testMalformattedFile** - use WaitJobStatusNotIn() and include 'QUEUED' state in parameter instead of using getjobstatus()

**testMultiPageJobState** - use WaitJobStatusNotIn() and include 'QUEUED' state in parameter instead of using getjobstatus()


Thank you!
