### ISSUE TITLE
Testing order is incorrect.

### ISSUE THREAD

**Issue by YasuhiroFuruta** [google/cloudprint_logocert#56]
Testing order is critically incorrect, e.g. testClosedPaperTray() before testOpenPaperTray().
(testOpenPaperTray() end with tray open state, and testClosedPaperTray() expects begining with tray open state.)

Currently, the testing framework sorts the test cases alphabetically.
I think the test cases should be sorted by the line number to resolve this issue.

**Comment by kdlucas** [comment]
Because we are using Python's Unit test to execute each test, order is not guaranteed. Each test may require some manual intervention to get the printer into the correct starting state for a specific test. Each test should not depend on the results of another test in order to get the printer into a specific state.
