### ISSUE TITLE
401 Error: invalid_client

### ISSUE THREAD

**Issue by iamoklo** [google/cloudprint_logocert#87]
Dear kdlucas,

![401 error invalid_client](https://cloud.githubusercontent.com/assets/22787996/19674301/b1496eaa-9ab9-11e6-8233-dcb11cb710bf.png)

Error: invalid_client
The OAuth client was not found.

Request Details
scope=https://www.googleapis.com/auth/cloudprint https://spreadsheets.google.com/feeds/
response_type=code
redirect_uri=urn:ietf:wg:oauth:2.0:oob
client_id=<279605758295-obimtqv377dn6ao60r9blqvkrge4d8qo.apps.googleusercontent.com>
That’s all we know.

Please help me to check this, thanks~

**Comment by kdlucas** [comment]
Did you set up the client you are using in the Google Developers console? It seems like it may not be set up yet. Follow the instructions in the README file for setting up the test client in the Google Developers console. Mainly these instructions:

1. Test Account - Use a test account that uses Gmail, in order to properly
authenticate against Google properties and also use OAuth2 credentials. Once
you have obtained a test account, obtain OAuth2 credentials from the Google
Developers Console. You'll also need a 2nd test account, without the OAuth2
credentials.

- Log in with your test account at https://accounts.google.com/
- Access the Google Developers Console: https://console.developers.google.com
- Create a project
- Access the project you just created
- Select the APIs & auth tab
- Select the Credentials link
- Two tokens are needed: under Client ID for native applications, copy the
-- Client ID
-- Client Secret

And then add the gmail account, password, Client ID, and Client Secret to the USER section in the _config.py file.

**Comment by iamoklo** [comment]
OK, I can run and get pre-test results Now.
Thanks a lot ! (I   ignore "RunAfter24Hours" first.)
 
  suite.addTest(unittest.makeSuite(SystemUnderTest))
  suite.addTest(unittest.makeSuite(Privet))
  suite.addTest(unittest.makeSuite(PreRegistration))
  suite.addTest(unittest.makeSuite(Registration))
  suite.addTest(unittest.makeSuite(PostRegistration))
  suite.addTest(unittest.makeSuite(LocalDiscovery))
  suite.addTest(unittest.makeSuite(LocalPrinting))
  suite.addTest(unittest.makeSuite(ChromePrinting))
  suite.addTest(unittest.makeSuite(Printer))
  suite.addTest(unittest.makeSuite(PrinterState))
  suite.addTest(unittest.makeSuite(JobState))
  suite.addTest(unittest.makeSuite(Printing))
  suite.addTest(unittest.makeSuite(Unregister))
  suite.addTest(unittest.makeSuite(PostUnregister))
