### ISSUE TITLE
testChromePrintPageRange and testLocalPrintPageRange issue

### ISSUE THREAD

**Issue by marctan** [google/cloudprint_logocert#95]
Hi Kelly/GCPTeam,

We are having this weird issue under testChromePrintPageRange and testLocalPrintPageRange. This test will try to set the page range to 2-3 but as you can see from the attached screenshot, it failed to do that.

These two tests are frequently failing using Windows 10. We are not sure if this is OS related. We've tried running this test using Windows 7 and everything works fine, there are no failures. We've also tried setting the page range manually and it works fine. We also suspect that this is a network connection related issue. Our internet connection is sometimes slow so maybe that's the cause of this failure or maybe this is a webdriver/selenium issue?.  

**Windows 10 - Fail**
![testlocalprintpagerange failure - win10](https://cloud.githubusercontent.com/assets/19194749/20959008/c9e66340-bc93-11e6-9982-e5ae56741cc5.png)

**Windows 10 - Fail**
![testchromeprintpagerange failure - win10](https://cloud.githubusercontent.com/assets/19194749/20959033/d9215a40-bc93-11e6-8450-5840eb778e86.png)

**Windows 7 - Success**
![testchromeprintpagerange - success - windows 7](https://cloud.githubusercontent.com/assets/19194749/20959004/c0b18bb0-bc93-11e6-9adf-b9d95cf22543.png)

Thanks,
Marc

**Comment by kdlucas** [comment]
Marc,

We'll be pushing out a whole new branch soon that will by-pass using
ChromeDriver, and will speak directly to the GCP Services and the printer.

You can try it now by downloading the branch called logocert_api. Try that
and see how it works for you.

It changes some of the way of doing things, like now you actually set the
suites inside the _config.py file.



Kelly
kdLucas

**Comment by marctan** [comment]
Hi Kelly,

This change is great and more robust compared to the older tool. I will
test this as soon as I can. I am currently waiting for the machines I need
to be available.

Regards,
Marc

**Comment by kdlucas** [comment]
Great, we'd like any feedback you can give us on version 2.0 of the tool.

**Comment by marctan** [comment]
Hi Kelly,

Here's what we've found while running the test tool 2.0:

During startup of the tool we've encountered this error:
![ty info error](https://cloud.githubusercontent.com/assets/19194749/21168424/d4c4f35c-c1ee-11e6-913c-848073fd5dcd.png)

And there's also another error which will only show if the printer model/name has a Space (' ') in config.py

![printer name with space error](https://cloud.githubusercontent.com/assets/19194749/21168478/3673986a-c1ef-11e6-91a8-ce7748ff19f8.png)


Thanks,
Marc

**Comment by lrbom** [comment]
Hi Marc,

I am the developer of the logocert_api branch.

This branch is not quite production ready yet. All existing test coverage should be there, but it's still undergoing code reviews and will need to be tested thoroughly after. This branch will continue to see quite a bit of changes until it is fully ready. Also, I've not started testing logocert_api on Windows yet. The  arrow and random character strings are used for colorizing text in Unix. Please bear with me while I push through testing in the coming weeks.

However, It is awesome to see this branch being Alpha-tested and I am happy to hear feedback from you and help along the way.

Addressing the issues you encountered:

Startup error: 

- The setup code has been replaced in the past week (among many other updates) and the error should not occur anymore. Please pull from the latest logocert_api branch.

Registration error:

- From looking at your Privet services, I'm guessing that printer name you have in _config.py is 'ModelName' and the error occurs when 'ModelName ' is used. What is likely happening is that you already have registered printers under your test account that start with 'ModelName '.

- For this test specifcally, the GCP /search interface is used to find all registered printers under your test account that starts with the _config.py name you've set. The test expects this list to be empty because the device should not be registered yet. Since there are other similarly named printers registered under your test account, it's returning an non-empty list and thus failing. 

- If this indeed is the case, all you have to do is to keep your test account clean of all printers except the one you are currently testing. In other words, only the printer you are testing should be registered under your account during the time of testing (only for the suites that require the printer to be registered however). I am open to adding an update to strictly match the specified printer name also so other printers can stay registered.

Hopefully this solves your problems!

Cheers,
Kevin

**Comment by kdlucas** [comment]
Marc, please grab the latest source and try again, as we want to get as much feedback in version 2.0 of the tool on as many platforms as possible. I think most of our development has been on Linux, so it would be interesting to get OS X or Windows users to provide some feedback.

**Comment by kdlucas** [comment]
Note: once we merge the logocert_api branch back into the main branch, we'll close this issue.

**Comment by marctan** [comment]
I apologize I wasn't able to perform this test on the new tool. Was really
busy with other works. I've already introduced this new tool with our test
engineers and I think they're already planning to perform it.

Btw, you may close this issue now since this specific test already passed
the last time I've tried it (old tool).

Thanks!

**Comment by kdlucas** [comment]
Sounds good, and thanks for the update.
